HW1. Layout of the catalog and detailed page
NotLostInCode/internship-ibs pull request #1
Opened 2023-12-29 15:10 UTC by NotLostInCode

2024-01-09 14:10 UTC, st-slav requested changes

2024-01-09 14:10 UTC, st-slav commented on css/reset.css
> +    /* display: inline-block; */
лишние комментарии лучше удалять

2024-01-09 14:10 UTC, st-slav commented on index.html
> +                        <img class="product__img" src="images/product.png" alt="">
alt лучше не игнорировать

2024-01-09 14:10 UTC, st-slav commented on index.html
> +               <div class="product__element">
возможно section или article здесь более подходящий тег

2024-01-09 14:10 UTC, st-slav commented on detailed.html
> +                                    <img src="icons/decrement.svg" alt="">
alt

2024-01-09 14:10 UTC, st-slav commented on detailed.html
> +                                    <img src="icons/increment.svg" alt="">
alt

2024-01-09 14:10 UTC, st-slav commented on detailed.html
> +                                <img src="icons/favorite.svg" alt="" class="detailed-product__favorite-icon">
alt

2024-01-10 07:20 UTC, Anton-Gadiyatov commented on css/style.css
> +@import url('https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700;900&display=swap');
https://web.dev/articles/font-best-practices?hl=ru
почитать для общего развития

2024-01-10 07:41 UTC, Anton-Gadiyatov commented on css/style.css
> +.header__search-input {}
пустые лучше не оставлять

2024-01-10 07:41 UTC, Anton-Gadiyatov commented on css/style.css
> +}
пустой

2024-01-10 07:41 UTC, Anton-Gadiyatov commented on css/style.css
https://doka.guide/css/rem-em/#pochemu-luchshe-ispolzovat-em-i-rem-vmesto-px-s-tochki-zreniya-dostupnosti-interfeysa
в данном случае изменять не нужно, но на будущее

2024-01-10 07:41 UTC, Anton-Gadiyatov commented on detailed.html
> +                    <img class="detailed-product__img" src="images/detail-product.png" alt="detailed-product">
неверная ссылка на изображение

2024-01-11 10:13 UTC, st-slav approved these changes

2024-01-11 10:13 UTC, merged