HW2. Adding logic to JS and conflict resolution
NotLostInCode/internship-ibs pull request #3
Opened 2024-01-11 11:20 UTC by NotLostInCode

2024-01-12 10:58 UTC, Anton-Gadiyatov requested changes

2024-01-12 10:58 UTC, Anton-Gadiyatov commented on src/js/catalog.js
> +const products = await getItemsCatalog()
а что случится по коду дальше, если "сервер" выдаст 500тую ошибку

2024-01-12 10:58 UTC, Anton-Gadiyatov commented on src/js/catalog.js
> +}
было бы здорово вынести в отдельный файл и чтобы функция принимала в себя (данные, родительский элемент)

2024-01-12 10:58 UTC, Anton-Gadiyatov commented on src/js/detail.js
> +const product = await getItemDetail(id)
а что случится по коду дальше, если "сервер" выдаст 500тую ошибку

2024-01-12 10:58 UTC, Anton-Gadiyatov commented on src/js/detail.js
> +`
лучше вынести в отдельную функцию по созданию элемента, которая  принимает в себя (данные, родительский элемент)

2024-01-12 10:58 UTC, Anton-Gadiyatov commented on src/js/search.js
по хорошему нужно фильтровать полученные с сервера данные и на основании этих данных уже перерисовывать товары

2024-01-12 21:48 UTC, NotLostInCode commented on src/js/catalog.js
> +const products = await getItemsCatalog()
> а что произойдет по коду дальше, если "сервер" выдаст 500тую ошибку

Исправил

2024-01-12 21:48 UTC, NotLostInCode commented on src/js/detail.js
> +const product = await getItemDetail(id)
> а что произойдет по коду дальше, если "сервер" выдаст 500тую ошибку

Исправил

2024-01-12 21:48 UTC, NotLostInCode commented on src/js/detail.js
> +`
> лучше вынести в отдельную функцию по созданию элемента, который принимает в себя (данные, родительский элемент)

Исправил

2024-01-12 21:49 UTC, NotLostInCode commented on src/js/search.js
> по хорошему нужно фильтровать полученные с сервера данные и на основании этих данных уже перерисовывать товары

Исправил

2024-01-15 06:42 UTC, st-slav approved these changes

2024-01-15 06:42 UTC, st-slav commented on src/js/detail.js
> +const id = pathname.split('/').pop()
можно использовать URLSearchParams
https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams

2024-01-15 06:44 UTC, merged