HW5. Adding react
NotLostInCode/internship-ibs pull request #6
Opened 2024-01-18 13:54 UTC by NotLostInCode

2024-01-19 14:38 UTC, Anton-Gadiyatov requested changes

2024-01-19 14:38 UTC, Anton-Gadiyatov commented on src/App.test.tsx
лучше удалить, раз не используется, тем более тест не пройдёт

2024-01-19 14:38 UTC, Anton-Gadiyatov commented on src/api/api.ts
Тут нужно типизировать ответ
https://bobbyhadz.com/blog/typescript-http-request-axios#making-http-get-requests-with-axios-in-typescript

2024-01-19 14:38 UTC, Anton-Gadiyatov commented on src/components/Actions/Actions.tsx
А какие стили он подтягивает тут, если Actions.module.css пустой?

2024-01-19 14:38 UTC, Anton-Gadiyatov commented on src/components/Search/Search.tsx
> +        console.log(input)
Забыл убрать console.log

2024-01-19 14:38 UTC, Anton-Gadiyatov commented on src/components/Search/Search.tsx
> +        debouncedHandleSearch(input);
сюда тоже лучше inputValue передавать

2024-01-19 14:38 UTC, Anton-Gadiyatov commented on src/features/Catalog/Catalog.tsx
> +export type ProductType = {
Типы которые используются в нескольких местах, лучше для них создать отдельную папочку types и там хранить, там тоже можно разбить по логическим сущностям, а потом импортировать в axious и в компоненты

2024-01-19 14:38 UTC, Anton-Gadiyatov commented on src/features/Catalog/Catalog.tsx
> +    const handleError = (message: string) => {
Это уже выглядит как небольшая компонента, которую можно вынести отдельно

2024-01-19 14:38 UTC, Anton-Gadiyatov commented on src/features/Catalog/Catalog.tsx
> +
Тут можно сделать проверку на наличие ошибки что-то типа
if (error) {
  return <p className={styles.errorMessage}>Произошла ошибка при загрузке данных</p>
}
Чтобы дальше нее использовать несколько тернарников подряд, этого стараются не делать, потому что их сложно понимать, когда их больше чем 1

2024-01-19 14:38 UTC, Anton-Gadiyatov commented on src/features/Catalog/Detail/Detail.tsx
Смотреть комментарии к компоненту Catalog

2024-01-19 18:21 UTC, NotLostInCode commented on src/App.test.tsx
Исправил

2024-01-19 18:21 UTC, NotLostInCode commented on src/api/api.ts
Исправил

2024-01-19 18:21 UTC, NotLostInCode commented on src/components/Actions/Actions.tsx
Исправил

2024-01-19 18:21 UTC, NotLostInCode commented on src/components/Search/Search.tsx
> +        console.log(input)
Исправил

2024-01-19 18:21 UTC, NotLostInCode commented on src/components/Search/Search.tsx
> +        debouncedHandleSearch(input);
Исправил

2024-01-19 18:21 UTC, NotLostInCode commented on src/features/Catalog/Catalog.tsx
> +export type ProductType = {
> Типы которые используются в нескольких местах, лучше для них создать отдельную папочку types и там хранить, там тоже можно разбить по логическим сущностям, а потом импортировать в axious и в компоненты

Исправил

2024-01-19 18:21 UTC, NotLostInCode commented on src/features/Catalog/Catalog.tsx
> +    const handleError = (message: string) => {
> Это уже выглядит как небольшая компонента, которую можно вынести отдельно

Исправил

2024-01-19 18:22 UTC, NotLostInCode commented on src/features/Catalog/Catalog.tsx
> +
> Тут можно сделать проверку на наличие ошибки что-то типа if (error) { return
> 
> Произошла ошибка при загрузке данных
> 
> 
> }
> Чтобы дальше нее использовать несколько тернарников подряд, этого стараются не делать, потому что их сложно понимать, когда их больше чем 1

Исправил

2024-01-19 18:22 UTC, NotLostInCode commented on src/features/Catalog/Detail/Detail.tsx
> Смотреть комментарии к компоненту Catalog

Исправил

2024-01-23 08:42 UTC, st-slav requested changes

2024-01-23 08:42 UTC, st-slav commented on package.json
> +    "@testing-library/jest-dom": "^5.17.0",
@testing-library наверно можно удалить

2024-01-23 08:42 UTC, st-slav commented on package.json
> +    "@types/react-router-dom": "^5.3.3",
@types надо унести в devDependencies

2024-01-23 08:42 UTC, st-slav commented on package.json
> +    "react-scripts": "5.0.1",
react-scripts надо унести в devDependencies

2024-01-23 08:42 UTC, st-slav commented on package.json
> +    "typescript": "^4.9.5",
typescript надо унести в devDependencies (по идее должно работать, но тут не уверен, надо проверить!)

2024-01-23 08:42 UTC, st-slav commented on src/components/Detail/Detail.tsx
> +            {!item || Object.keys(item).length === 0
а в каком случае может вернуться пустой объект?

2024-01-23 08:42 UTC, st-slav commented on src/components/Error/Error.tsx
> +    text: boolean | string
boolean мне кажется не совсем тот тип который может быть в поле с именем text

2024-01-23 08:42 UTC, st-slav commented on src/components/Search/Search.tsx
> +    const debouncedHandleSearch = useDebounce((input: string) => {
думаю так тоже будет работать:
const debouncedHandleSearch = useDebounce(handleSearch, 1000);

2024-01-23 08:42 UTC, st-slav commented on src/components/Search/Search.tsx
> +                <svg
давай svg вынесем в отдельный svg файл и папку assets 
https://create-react-app.dev/docs/adding-images-fonts-and-files/#adding-svgs

2024-01-23 08:42 UTC, st-slav commented on src/features/CatalogPage/CatalogPage.tsx
> +    useEffect(() => {
здесь можно использовать useMemo, т. к. если удалять, то полный список items с сервера будет потерян

2024-01-23 08:42 UTC, st-slav commented on src/features/DetailPage/DetailPage.tsx
> +            const params = new URLSearchParams(window.location.search);
т. к. используется react-router, лучше использовать его хуки для получения строки из location

2024-01-23 08:42 UTC, st-slav commented on src/hooks/useModal.tsx
> +    instance.interceptors.response.use(
я бы завернул это в useEffect без параметров чтоб только один раз случалось, но на сколько это будет работать, не проверял, надо проверить

2024-01-23 08:42 UTC, st-slav commented on src/app/App.tsx
> +import {CatalogPage} from "../features/CatalogPage/CatalogPage";
страницы полностью лучше хранить в папке pages и потом собирать их из компонентов

2024-01-23 08:42 UTC, st-slav commented on src/app/App.tsx
> +import {DetailPage} from "../features/DetailPage/DetailPage";
страницы полностью лучше хранить в папке pages и потом собирать их из компонентов

2024-01-23 08:46 UTC, st-slav commented on src/components/Catalog/Catalog.tsx
> +            {!items.length
эту проверку можно вынести на уровень выше в CatalogPage

2024-01-23 08:47 UTC, st-slav commented on src/components/Detail/Detail.tsx
> +            {!item || Object.keys(item).length === 0
эту проверку можно вынести на уровень выше в DetailPage

2024-01-23 17:57 UTC, NotLostInCode commented on package.json
> +    "@testing-library/jest-dom": "^5.17.0",
Исправил

2024-01-23 17:58 UTC, NotLostInCode commented on package.json
> +    "react-scripts": "5.0.1",
Исправил

2024-01-23 17:58 UTC, NotLostInCode commented on package.json
> +    "@types/react-router-dom": "^5.3.3",
Исправил

2024-01-23 17:58 UTC, NotLostInCode commented on package.json
> +    "typescript": "^4.9.5",
Исправил

2024-01-23 17:58 UTC, NotLostInCode commented on src/components/Detail/Detail.tsx
> +            {!item || Object.keys(item).length === 0
Исправил

2024-01-23 17:58 UTC, NotLostInCode commented on src/features/CatalogPage/CatalogPage.tsx
> +    useEffect(() => {
Исправил

2024-01-23 17:58 UTC, NotLostInCode commented on src/features/DetailPage/DetailPage.tsx
> +            const params = new URLSearchParams(window.location.search);
Исправил

2024-01-23 17:58 UTC, NotLostInCode commented on src/app/App.tsx
> +import {CatalogPage} from "../features/CatalogPage/CatalogPage";
Исправил

2024-01-23 17:58 UTC, NotLostInCode commented on src/app/App.tsx
> +import {DetailPage} from "../features/DetailPage/DetailPage";
Исправил

2024-01-23 17:58 UTC, NotLostInCode commented on src/components/Catalog/Catalog.tsx
> +            {!items.length
Исправил

2024-01-23 17:58 UTC, NotLostInCode commented on src/components/Detail/Detail.tsx
> +            {!item || Object.keys(item).length === 0
Исправил

2024-01-23 18:14 UTC, Anton-Gadiyatov approved these changes

2024-01-24 13:25 UTC, st-slav approved these changes

2024-01-24 13:26 UTC, merged

2024-01-24 13:36 UTC, st-slav commented on src/pages/DetailPage/DetailPage.tsx
> +            const id = params.get('id');
https://reactrouter.com/en/main/hooks/use-params