HW6. Adding RTK
NotLostInCode/internship-ibs pull request #7
Opened 2024-01-24 18:41 UTC by NotLostInCode

2024-01-24 18:57 UTC, Anton-Gadiyatov requested changes

2024-01-24 18:57 UTC, Anton-Gadiyatov commented on src/components/Catalog/Catalog.tsx
> +                    <article className={styles.productElement} key={index}>
product.id лучше обратно вернуть, index не надёжен для использования в качестве ключа

2024-01-24 18:57 UTC, Anton-Gadiyatov commented on src/components/Catalog/catalog-reducer.ts
> +                state.items.push(...action.payload)
тут можно напрямую state.items = action.payload

2024-01-24 18:57 UTC, Anton-Gadiyatov commented on src/components/Catalog/catalog-reducer.ts
> +                state.error = action.error.message ? action.error.message : 'Ошибка при получении данных'
Тут лучше просто "Ошибка при получении данных", чтобы пользователь не видел внутренних ошибок, это не всегда безопасно.

2024-01-24 18:57 UTC, Anton-Gadiyatov commented on src/components/Loader/Loader.tsx
Тут в пропс loading не нужно, можно без всяких пропсов

2024-01-24 18:57 UTC, Anton-Gadiyatov commented on src/pages/CatalogPage/CatalogPage.tsx
> +            <Loader loading={loading} />
А тут {loading && <Loader />}

2024-01-24 18:57 UTC, Anton-Gadiyatov commented on src/pages/CatalogPage/CatalogPage.tsx
> +            {!loading && !error && !!items.length && <Catalog items={items} />}
тут можно просто items.length, без "!!"

2024-01-24 18:57 UTC, Anton-Gadiyatov commented on src/pages/DetailPage/DetailPage.tsx
> +    let {id} = useParams()
тут const, вместо let

2024-01-25 08:00 UTC, NotLostInCode commented on src/components/Catalog/Catalog.tsx
> +                    <article className={styles.productElement} key={index}>
Исправил

2024-01-25 08:00 UTC, NotLostInCode commented on src/components/Catalog/catalog-reducer.ts
> +                state.items.push(...action.payload)
Исправил

2024-01-25 08:00 UTC, NotLostInCode commented on src/components/Catalog/catalog-reducer.ts
> +                state.error = action.error.message ? action.error.message : 'Ошибка при получении данных'
Исправил

2024-01-25 08:00 UTC, NotLostInCode commented on src/components/Loader/Loader.tsx
Исправил

2024-01-25 08:00 UTC, NotLostInCode commented on src/pages/CatalogPage/CatalogPage.tsx
> +            <Loader loading={loading} />
Исправил

2024-01-25 08:00 UTC, NotLostInCode commented on src/pages/CatalogPage/CatalogPage.tsx
> +            {!loading && !error && !!items.length && <Catalog items={items} />}
Исправил

2024-01-25 08:00 UTC, NotLostInCode commented on src/pages/DetailPage/DetailPage.tsx
> +    let {id} = useParams()
Исправил

2024-01-26 14:08 UTC, st-slav approved these changes

2024-01-26 14:08 UTC, merged