HW7. Requesting data using rtk query
NotLostInCode/internship-ibs pull request #8
Opened 2024-01-29 17:20 UTC by NotLostInCode

2024-02-01 08:31 UTC, st-slav requested changes

2024-02-01 08:31 UTC, st-slav commented on src/pages/CatalogPage/CatalogPage.tsx
> +        dispatch(fetchItems(data.content))
думаю что дополнительно не стоит класть в стор полученные данные, можно их использовать напрямую из хука useGetItemsCatalogQuery()

2024-02-01 08:31 UTC, st-slav commented on src/pages/DetailPage/DetailPage.tsx
> +         dispatch(fetchItem(data.content))
думаю что дополнительно не стоит класть в стор полученные данные, можно их использовать напрямую из хука useGetItemDetailQuery()

2024-02-01 08:31 UTC, st-slav commented on src/app/App.tsx
> +import Box from "@mui/material/Box";
давай так же темизируем наше приложение и попробуем воспользоваться темой в каком-нибудь из компонентов
https://mui.com/material-ui/customization/theming/

2024-02-01 16:25 UTC, NotLostInCode commented on src/pages/CatalogPage/CatalogPage.tsx
> +        dispatch(fetchItems(data.content))
Исправил

2024-02-01 16:25 UTC, NotLostInCode commented on src/pages/DetailPage/DetailPage.tsx
> +         dispatch(fetchItem(data.content))
Исправил

2024-02-01 16:25 UTC, NotLostInCode commented on src/app/App.tsx
> +import Box from "@mui/material/Box";
Сделал

2024-02-02 07:52 UTC, st-slav approved these changes

2024-02-02 18:44 UTC, merged